from FileHandler import FileHandler
import sys
import lexer

class PDA:
    def __init__(self, states, alphabet, stack_alphabet, initial_state, initial_stack_symbol, transitions, final_states):
        self.states = states
        self.alphabet = alphabet
        self.stack_alphabet = stack_alphabet
        self.initial_state = initial_state
        self.initial_stack_symbol = initial_stack_symbol
        self.transitions = transitions
        self.final_states = final_states
        self.stack = []

    def reset(self):
        self.stack = [self.initial_stack_symbol]

    def process_input(self, input_string):
        current_state = self.initial_state
        self.reset()

        for symbol in input_string:
            transition_key = (current_state, symbol, self.stack[-1] if self.stack else None)
            print(self.stack)
            print(symbol)
            # print(transition_key)
            if transition_key in self.transitions:
                action = self.transitions[transition_key]
                self.stack.pop()
                if action[1] != 'epsilon':
                    # print(action[1])
                    for stack_symbol in action[1][::-1]:
                        self.stack.append(stack_symbol)
                current_state = action[0]
                print(current_state)
                # self.stack.pop()
            else:
                return False

        return len(self.stack) == 1


def main():
    fh = FileHandler()
    # pda = PDA()

    states = {'q0', 'q1', 'q2', 'q3'}
    alphabet = {'<', '>', '/', ' ', 'h', 't', 'm', 'l'}
    stack_alphabet = {'tag_open', 'tag_close'}
    initial_state = 'qkurung'
    initial_stack_symbol = 'Z'
    transitions = {
        # HTML
        ('qkurung', 'HTML_OPEN', 'Z'): ('qhtml', ('A', 'Z')),
        ('qhtml', 'CLASS', 'A'): ('qhtml', 'A'),
        ('qhtml', 'ID', 'A'): ('qhtml', 'A'),
        ('qhtml', 'NAME', 'A'): ('qhtml', 'A'),
        ('qhtml', 'KURUNG_TUTUP', 'A'): ('qkurunghead', 'A'),
        ('qkurung', 'HTML_CLOSE', 'A'): ('qkurung', 'epsilon'),

        ('qkurunghead', 'HEAD_OPEN', 'A'): ('qhead', ('B', 'A')),
        ('qhead', 'CLASS', 'B'): ('qhead', 'A'),
        ('qhead', 'ID', 'B'): ('qhead', 'A'),
        ('qhead', 'STYLE', 'B'): ('qhead', 'A'),
        ('qhead', 'KURUNG_TUTUP', 'B'): ('qkurunghead', 'B'),
        ('qkurunghead', 'HEAD_CLOSE', 'B'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'BODY_OPEN', 'A'): ('qbody', ('C', 'A')),
        ('qbody', 'CLASS', 'C'): ('qbody', 'C'),
        ('qbody', 'ID', 'C'): ('qbody', 'C'),
        ('qbody', 'STYLE', 'C'): ('qbody', 'C'),
        ('qbody', 'KURUNG_TUTUP', 'C'): ('qkurungbody', 'C'),
        ('qkurungbody', 'BODY_CLOSE', 'C'): ('qkurung', 'epsilon'),

        ('qkurunghead', 'TITLE_OPEN', 'B'): ('qtitle', ('D', 'B')),
        ('qtitle', 'CLASS', 'D'): ('qtitle', 'D'),
        ('qtitle', 'ID', 'D'): ('qtitle', 'D'),
        ('qtitle', 'STYLE', 'D'): ('qtitle', 'D'),
        ('qtitle', 'KURUNG_TUTUP', 'D'): ('qkurunghead', 'D'),
        ('qkurunghead', 'TITLE_CLOSE', 'D'): ('qkurunghead', 'epsilon'),

        ('qkurunghead', 'SCRIPT_OPEN', 'B'): ('qscripthead', ('E', 'B')),
        ('qkurungbody', 'SCRIPT_OPEN', 'C'): ('qscriptbody', ('E', 'C')),
        ('qscripthead', 'CLASS', 'E'): ('qscripthead', 'E'),
        ('qscriptbody', 'CLASS', 'E'): ('qscriptbody', 'E'),
        ('qscripthead', 'ID', 'E'): ('qscripthead', 'E'),
        ('qscriptbody', 'ID', 'E'): ('qscriptbody', 'E'),
        ('qscripthead', 'STYLE', 'E'): ('qscripthead', 'E'),
        ('qscriptbody', 'STYLE', 'E'): ('qscriptbody', 'E'),
        ('qscripthead', 'KURUNG_TUTUP', 'E'): ('qkurunghead', 'E'),
        ('qscriptbody', 'KURUNG_TUTUP', 'E'): ('qkurungbody', 'E'),
        ('qkurunghead', 'SCRIPT_CLOSE', 'E'): ('qkurunghead', 'epsilon'),
        ('qkurungbody', 'SCRIPT_CLOSE', 'E'): ('qkurungbody', 'epsilon'),


        ('qkurungbody', 'H1_OPEN', 'C'): ('qh1', ('F', 'C')),
        ('qh1', 'CLASS', 'F'): ('qh1', 'F'),
        ('qh1', 'ID', 'F'): ('qh1', 'F'),
        ('qh1', 'STYLE', 'F'): ('qh1', 'F'),
        ('qh1', 'KURUNG_TUTUP', 'F'): ('qkurungbody', 'F'),
        ('qkurungbody', 'H1_CLOSE', 'F'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'H2_OPEN', 'C'): ('qh2', ('G', 'C')),
        ('qh2', 'CLASS', 'G'): ('qh2', 'G'),
        ('qh2', 'ID', 'G'): ('qh2', 'G'),
        ('qh2', 'STYLE', 'G'): ('qh2', 'G'),
        ('qh2', 'KURUNG_TUTUP', 'G'): ('qkurungbody', 'G'),
        ('qkurungbody', 'H2_CLOSE', 'G'): ('qkurungbody', 'epsilon'),
        
        ('qkurungbody', 'H3_OPEN', 'C'): ('qh3', ('H', 'C')),
        ('qh3', 'CLASS', 'H'): ('qh3', 'H'),
        ('qh3', 'ID', 'H'): ('qh3', 'H'),
        ('qh3', 'STYLE', 'H'): ('qh3', 'H'),
        ('qh3', 'KURUNG_TUTUP', 'H'): ('qkurungbody', 'H'),
        ('qkurungbody', 'H3_CLOSE', 'H'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'H4_OPEN', 'C'): ('qh4', ('I', 'C')),
        ('qh4', 'CLASS', 'I'): ('qh4', 'I'),
        ('qh4', 'ID', 'I'): ('qh4', 'I'),
        ('qh4', 'STYLE', 'I'): ('qh4', 'I'),
        ('qh4', 'KURUNG_TUTUP', 'I'): ('qkurungbody', 'I'),
        ('qkurungbody', 'H4_CLOSE', 'I'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'H5_OPEN', 'C'): ('qh5', ('J', 'C')),
        ('qh5', 'CLASS', 'J'): ('qh5', 'J'),
        ('qh5', 'ID', 'J'): ('qh5', 'J'),
        ('qh5', 'STYLE', 'J'): ('qh5', 'J'),
        ('qh5', 'KURUNG_TUTUP', 'J'): ('qkurungbody', 'J'),
        ('qkurungbody', 'H5_CLOSE', 'J'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'H6_OPEN', 'C'): ('qh6', ('K', 'C')),
        ('qh6', 'CLASS', 'K'): ('qh6', 'K'),
        ('qh6', 'ID', 'K'): ('qh6', 'K'),
        ('qh6', 'STYLE', 'K'): ('qh6', 'K'),
        ('qh6', 'KURUNG_TUTUP', 'K'): ('qkurungbody', 'K'),
        ('qkurungbody', 'H6_CLOSE', 'K'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'P_OPEN', 'C'): ('qp', ('L', 'C')),
        ('qp', 'CLASS', 'L'): ('qp', 'L'),
        ('qp', 'ID', 'L'): ('qp', 'L'),
        ('qp', 'STYLE', 'L'): ('qp', 'L'),
        ('qp', 'KURUNG_TUTUP', 'L'): ('qkurungbody', 'L'),
        ('qkurungbody', 'P_CLOSE', 'L'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'EM_OPEN', 'C'): ('qem', ('M', 'C')),
        ('qem', 'CLASS', 'M'): ('qem', 'M'),
        ('qem', 'ID', 'M'): ('qem', 'M'),
        ('qem', 'STYLE', 'M'): ('qem', 'M'),
        ('qem', 'KURUNG_TUTUP', 'M'): ('qkurungbody', 'M'),
        ('qkurungbody', 'EM_CLOSE', 'M'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'B_OPEN', 'C'): ('qem', ('N', 'C')),
        ('qem', 'CLASS', 'N'): ('qem', 'N'),
        ('qem', 'ID', 'N'): ('qem', 'N'),
        ('qem', 'STYLE', 'N'): ('qem', 'N'),
        ('qem', 'KURUNG_TUTUP', 'N'): ('qkurungbody', 'N'),
        ('qkurungbody', 'B_CLOSE', 'N'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'ABBR_OPEN', 'C'): ('qabbr', ('O', 'C')),
        ('qabbr', 'CLASS', 'O'): ('qabbr', 'O'),
        ('qabbr', 'ID', 'O'): ('qabbr', 'O'),
        ('qabbr', 'STYLE', 'O'): ('qabbr', 'O'),
        ('qabbr', 'KURUNG_TUTUP', 'O'): ('qkurungbody', 'O'),
        ('qkurungbody', 'ABBR_CLOSE', 'O'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'STRONG_OPEN', 'C'): ('qstrong', ('P', 'C')),
        ('qstrong', 'CLASS', 'P'): ('qstrong', 'P'),
        ('qstrong', 'ID', 'P'): ('qstrong', 'P'),
        ('qstrong', 'STYLE', 'P'): ('qstrong', 'P'),
        ('qstrong', 'KURUNG_TUTUP', 'P'): ('qkurungbody', 'P'),
        ('qkurungbody', 'STRONG_CLOSE', 'P'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'SMALL_OPEN', 'C'): ('qsmall', ('Q', 'C')),
        ('qsmall', 'CLASS', 'Q'): ('qsmall', 'Q'),
        ('qsmall', 'ID', 'Q'): ('qsmall', 'Q'),
        ('qsmall', 'STYLE', 'Q'): ('qsmall', 'Q'),
        ('qsmall', 'KURUNG_TUTUP', 'Q'): ('qkurungbody', 'Q'),
        ('qkurungbody', 'SMALL_CLOSE', 'Q'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'DIV_OPEN', 'C'): ('qdiv', ('R', 'C')),
        ('qdiv', 'CLASS', 'R'): ('qdiv', 'R'),
        ('qdiv', 'ID', 'R'): ('qdiv', 'R'),
        ('qdiv', 'STYLE', 'R'): ('qdiv', 'R'),
        ('qdiv', 'KURUNG_TUTUP', 'R'): ('qkurungbody', 'R'),
        ('qkurungbody', 'DIV_CLOSE', 'R'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'A_OPEN', 'C'): ('qa', ('S', 'C')),
        ('qa', 'CLASS', 'S'): ('qa', 'S'),
        ('qa', 'ID', 'S'): ('qa', 'S'),
        ('qa', 'STYLE', 'S'): ('qa', 'S'),
        ('qa', 'KURUNG_TUTUP', 'S'): ('qkurungbody', 'S'),
        ('qkurungbody', 'A_CLOSE', 'S'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'BUTTON_OPEN', 'C'): ('qbutton', ('T', 'C')),
        ('qbutton', 'CLASS', 'T'): ('qbutton', 'T'),
        ('qbutton', 'ID', 'T'): ('qbutton', 'T'),
        ('qbutton', 'STYLE', 'T'): ('qbutton', 'T'),
        ('qbutton', 'KURUNG_TUTUP', 'T'): ('qkurungbody', 'T'),
        ('qkurungbody', 'BUTTON_CLOSE', 'T'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'FORM_OPEN', 'C'): ('qform', ('U', 'C')),
        ('qform', 'CLASS', 'U'): ('qform', 'U'),
        ('qform', 'ID', 'U'): ('qform', 'U'),
        ('qform', 'STYLE', 'U'): ('qform', 'U'),
        ('qform', 'KURUNG_TUTUP', 'U'): ('qkurungbody', 'U'),
        ('qkurungbody', 'AFORM_CLOSE', 'U'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'TABLE_OPEN', 'C'): ('qtable', ('V', 'C')),
        ('qtable', 'CLASS', 'V'): ('qtable', 'V'),
        ('qtable', 'ID', 'V'): ('qtable', 'V'),
        ('qtable', 'STYLE', 'V'): ('qtable', 'V'),
        ('qtable', 'KURUNG_TUTUP', 'V'): ('qkurungbody', 'V'),
        ('qkurungbody', 'TABLE_CLOSE', 'V'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'TR_OPEN', 'V'): ('qtr', ('W', 'V')),
        ('qtr', 'CLASS', 'W'): ('qtr', 'W'),
        ('qtr', 'ID', 'W'): ('qtr', 'W'),
        ('qtr', 'STYLE', 'W'): ('qtr', 'W'),
        ('qtr', 'KURUNG_TUTUP', 'W'): ('qkurungbody', 'W'),
        ('qkurungbody', 'TR_CLOSE', 'W'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'TD_OPEN', 'V'): ('qtd', ('X', 'V')),
        ('qtd', 'CLASS', 'X'): ('qtd', 'X'),
        ('qtd', 'ID', 'X'): ('qtd', 'X'),
        ('qtd', 'STYLE', 'X'): ('qtd', 'X'),
        ('qtd', 'KURUNG_TUTUP', 'X'): ('qkurungbody', 'X'),
        ('qkurungbody', 'TD_CLOSE', 'X'): ('qkurungbody', 'epsilon'),

        ('qkurungbody', 'TH_OPEN', 'V'): ('qth', ('Y', 'V')),
        ('qth', 'CLASS', 'Y'): ('qth', 'Y'),
        ('qth', 'ID', 'Y'): ('qth', 'Y'),
        ('qth', 'STYLE', 'Y'): ('qth', 'Y'),
        ('qth', 'KURUNG_TUTUP', 'Y'): ('qkurungbody', 'Y'),
        ('qkurungbody', 'TH_CLOSE', 'Y'): ('qkurungbody', 'epsilon'),


        # ('qhtml', 'CLASS', 'A'): ('qhtml', 'A'),
        # ('qhtml', 'CLASS', 'B'): ('qhtml', 'B'),
        # ('qhtml', 'CLASS', 'C'): ('qhtml', 'C'),
        # ('qhtml', 'CLASS', 'D'): ('qhtml', 'D'),
        # ('qhtml', 'CLASS', 'E'): ('qhtml', 'E'),
        # ('qhtml', 'CLASS', 'F'): ('qhtml', 'F'),
        # ('qhtml', 'CLASS', 'G'): ('qhtml', 'G'),
        # ('qhtml', 'CLASS', 'H'): ('qhtml', 'H'),
        # ('qhtml', 'CLASS', 'I'): ('qhtml', 'I'),
        # ('qhtml', 'CLASS', 'J'): ('qhtml', 'J'),
        # ('qhtml', 'CLASS', 'K'): ('qhtml', 'K'),
        # ('qhtml', 'CLASS', 'L'): ('qhtml', 'L'),
        # ('qhtml', 'CLASS', 'M'): ('qhtml', 'M'),
        # ('qhtml', 'CLASS', 'N'): ('qhtml', 'N'),
        # ('qhtml', 'CLASS', 'O'): ('qhtml', 'O'),
        # ('qhtml', 'CLASS', 'P'): ('qhtml', 'P'),
        # ('qhtml', 'CLASS', 'Q'): ('qhtml', 'Q'),
        # ('qhtml', 'CLASS', 'R'): ('qhtml', 'R'),
        # ('qhtml', 'CLASS', 'S'): ('qhtml', 'S'),
        # ('qhtml', 'CLASS', 'T'): ('qhtml', 'T'),
        # ('qhtml', 'CLASS', 'U'): ('qhtml', 'U'),
        # ('qhtml', 'CLASS', 'V'): ('qhtml', 'V'),
        # ('qhtml', 'CLASS', 'W'): ('qhtml', 'W'),
        # ('qhtml', 'CLASS', 'X'): ('qhtml', 'X'),
        # ('qhtml', 'CLASS', 'Y'): ('qhtml', 'Y'),
        # ('qlink', 'CLASS', 'a'): ('qlink', 'a'),
        # ('qhtml', 'CLASS', 'b'): ('qhtml', 'b'),
        # ('qhtml', 'CLASS', 'c'): ('qhtml', 'c'),
        # ('qimage', 'CLASS', 'd'): ('qimage', 'd'),

        # ('qhtml', 'ID', 'A'): ('qhtml', 'A'),
        # ('qhtml', 'ID', 'B'): ('qhtml', 'B'),
        # ('qhtml', 'ID', 'C'): ('qhtml', 'C'),
        # ('qhtml', 'ID', 'D'): ('qhtml', 'D'),
        # ('qhtml', 'ID', 'E'): ('qhtml', 'E'),
        # ('qhtml', 'ID', 'F'): ('qhtml', 'F'),
        # ('qhtml', 'ID', 'G'): ('qhtml', 'G'),
        # ('qhtml', 'ID', 'H'): ('qhtml', 'H'),
        # ('qhtml', 'ID', 'I'): ('qhtml', 'I'),
        # ('qhtml', 'ID', 'J'): ('qhtml', 'J'),
        # ('qhtml', 'ID', 'K'): ('qhtml', 'K'),
        # ('qhtml', 'ID', 'L'): ('qhtml', 'L'),
        # ('qhtml', 'ID', 'M'): ('qhtml', 'M'),
        # ('qhtml', 'ID', 'N'): ('qhtml', 'N'),
        # ('qhtml', 'ID', 'O'): ('qhtml', 'O'),
        # ('qhtml', 'ID', 'P'): ('qhtml', 'P'),
        # ('qhtml', 'ID', 'Q'): ('qhtml', 'Q'),
        # ('qhtml', 'ID', 'R'): ('qhtml', 'R'),
        # ('qhtml', 'ID', 'S'): ('qhtml', 'S'),
        # ('qhtml', 'ID', 'T'): ('qhtml', 'T'),
        # ('qhtml', 'ID', 'U'): ('qhtml', 'U'),
        # ('qhtml', 'ID', 'V'): ('qhtml', 'V'),
        # ('qhtml', 'ID', 'W'): ('qhtml', 'W'),
        # ('qhtml', 'ID', 'X'): ('qhtml', 'X'),
        # ('qhtml', 'ID', 'Y'): ('qhtml', 'Y'),
        # ('qlink', 'CLASS', 'a'): ('qlink', 'a'),
        # ('qhtml', 'CLASS', 'b'): ('qhtml', 'b'),
        # ('qhtml', 'CLASS', 'c'): ('qhtml', 'c'),
        # ('qimage', 'ID', 'd'): ('qimage', 'd'),

        # ('qhtml', 'STYLE', 'A'): ('qhtml', 'A'),
        # ('qhtml', 'STYLE', 'B'): ('qhtml', 'B'),
        # ('qhtml', 'STYLE', 'C'): ('qhtml', 'C'),
        # ('qhtml', 'STYLE', 'D'): ('qhtml', 'D'),
        # ('qhtml', 'STYLE', 'E'): ('qhtml', 'E'),
        # ('qhtml', 'STYLE', 'F'): ('qhtml', 'F'),
        # ('qhtml', 'STYLE', 'G'): ('qhtml', 'G'),
        # ('qhtml', 'STYLE', 'H'): ('qhtml', 'H'),
        # ('qhtml', 'STYLE', 'I'): ('qhtml', 'I'),
        # ('qhtml', 'STYLE', 'J'): ('qhtml', 'J'),
        # ('qhtml', 'STYLE', 'K'): ('qhtml', 'K'),
        # ('qhtml', 'STYLE', 'L'): ('qhtml', 'L'),
        # ('qhtml', 'STYLE', 'M'): ('qhtml', 'M'),
        # ('qhtml', 'STYLE', 'N'): ('qhtml', 'N'),
        # ('qhtml', 'STYLE', 'O'): ('qhtml', 'O'),
        # ('qhtml', 'STYLE', 'P'): ('qhtml', 'P'),
        # ('qhtml', 'STYLE', 'Q'): ('qhtml', 'Q'),
        # ('qhtml', 'STYLE', 'R'): ('qhtml', 'R'),
        # ('qhtml', 'STYLE', 'S'): ('qhtml', 'S'),
        # ('qhtml', 'STYLE', 'T'): ('qhtml', 'T'),
        # ('qhtml', 'STYLE', 'U'): ('qhtml', 'U'),
        # ('qhtml', 'STYLE', 'V'): ('qhtml', 'V'),
        # ('qhtml', 'STYLE', 'W'): ('qhtml', 'W'),
        # ('qhtml', 'STYLE', 'X'): ('qhtml', 'X'),
        # ('qhtml', 'STYLE', 'Y'): ('qhtml', 'Y'),
        # ('qlink', 'CLASS', 'a'): ('qlink', 'a'),
        # ('qhtml', 'CLASS', 'b'): ('qhtml', 'b'),
        # ('qhtml', 'CLASS', 'c'): ('qhtml', 'c'),
        # ('qimage', 'STYLE', 'd'): ('qimage', 'd'),

        # ('qhtml', 'TYPE_BUTTON', 'T'): ('qhtml', 'T'),
        # ('qhtml', 'TYPE_INPUT', 'e'): ('qhtml', 'e'),

        # ('qhtml', 'HREF', 'S'): ('qhtml', 'S'),
        # ('qimage', 'ALT', 'd'): ('qimage', 'd'),

        # ('qhtml', 'ACTION', 'U'): ('qhtml', 'U'),

        # ('qhtml', 'METHOD', 'U'): ('qhtml', 'U'),

        # ('qhtml', 'KURUNG_TUTUP', 'A'): ('qkurung', 'A'),
        # ('qhead', 'KURUNG_TUTUP', 'B'): ('qkurung', 'B'),
        # ('qbody', 'KURUNG_TUTUP', 'C'): ('qkurung', 'C'),
        # ('qtitle', 'KURUNG_TUTUP', 'D'): ('qkurung', 'D'),
        # ('qscript', 'KURUNG_TUTUP', 'E'): ('qkurung', 'E'),
        # ('qh1', 'KURUNG_TUTUP', 'F'): ('qkurung', 'F'),
        # ('qh2', 'KURUNG_TUTUP', 'G'): ('qkurung', 'G'),
        # ('qh3', 'KURUNG_TUTUP', 'H'): ('qkurung', 'H'),
        # ('qh4', 'KURUNG_TUTUP', 'I'): ('qkurung', 'I'),
        # ('qh5', 'KURUNG_TUTUP', 'J'): ('qkurung', 'J'),
        # ('qh6', 'KURUNG_TUTUP', 'K'): ('qkurung', 'K'),
        # ('qhp', 'KURUNG_TUTUP', 'L'): ('qkurung', 'L'),
        # ('qem', 'KURUNG_TUTUP', 'M'): ('qkurung', 'M'),
        # ('qb', 'KURUNG_TUTUP', 'N'): ('qkurung', 'N'),
        # ('qabbr', 'KURUNG_TUTUP', 'O'): ('qkurung', 'O'),
        # ('qstrong', 'KURUNG_TUTUP', 'P'): ('qkurung', 'P'),
        # ('qsmall', 'KURUNG_TUTUP', 'Q'): ('qkurung', 'Q'),
        # ('qdiv', 'KURUNG_TUTUP', 'R'): ('qkurung', 'R'),
        # ('qa', 'KURUNG_TUTUP', 'S'): ('qkurung', 'S'),
        # ('qbutton', 'KURUNG_TUTUP', 'T'): ('qkurung', 'T'),
        # ('qform', 'KURUNG_TUTUP', 'U'): ('qkurung', 'U'),
        # ('qtable', 'KURUNG_TUTUP', 'V'): ('qkurung', 'V'),
        # ('qtr', 'KURUNG_TUTUP', 'W'): ('qkurung', 'W'),
        # ('qtd', 'KURUNG_TUTUP', 'X'): ('qkurung', 'X'),
        # ('qth', 'KURUNG_TUTUP', 'Y'): ('qkurung', 'Y'),


        # ('qkurung', 'TITLE_OPEN', 'B'): ('qtitle', ('D', 'B')),
        # ('qkurung', 'TITLE_OPEN', 'E'): ('qtitle', ('D', 'E')),
        # ('qkurung', 'TITLE_OPEN', 'F'): ('qtitle', ('D', 'F')),
        # ('qkurung', 'TITLE_OPEN', 'G'): ('qtitle', ('D', 'G')),
        # ('qkurung', 'TITLE_OPEN', 'H'): ('qtitle', ('D', 'H')),
        # ('qkurung', 'TITLE_OPEN', 'I'): ('qtitle', ('D', 'I')),
        # ('qkurung', 'TITLE_OPEN', 'J'): ('qtitle', ('D', 'J')),
        # ('qkurung', 'TITLE_OPEN', 'K'): ('qtitle', ('D', 'K')),
        # ('qkurung', 'TITLE_OPEN', 'L'): ('qtitle', ('D', 'L')),
        # ('qkurung', 'TITLE_OPEN', 'M'): ('qtitle', ('D', 'M')),
        # ('qkurung', 'TITLE_OPEN', 'N'): ('qtitle', ('D', 'N')),
        # ('qkurung', 'TITLE_OPEN', 'O'): ('qtitle', ('D', 'O')),
        # ('qkurung', 'TITLE_OPEN', 'P'): ('qtitle', ('D', 'P')),
        # ('qkurung', 'TITLE_OPEN', 'Q'): ('qtitle', ('D', 'Q')),
        # ('qkurung', 'TITLE_OPEN', 'R'): ('qtitle', ('D', 'R')),
        # ('qkurung', 'TITLE_OPEN', 'S'): ('qtitle', ('D', 'S')),
        # ('qkurung', 'TITLE_OPEN', 'T'): ('qtitle', ('D', 'T')),
        # ('qkurung', 'TITLE_OPEN', 'U'): ('qtitle', ('D', 'U')),
        # ('qkurung', 'TITLE_OPEN', 'V'): ('qtitle', ('D', 'V')),
        # ('qkurung', 'TITLE_OPEN', 'W'): ('qtitle', ('D', 'W')),
        # ('qkurung', 'TITLE_OPEN', 'X'): ('qtitle', ('D', 'X')),
        # ('qkurung', 'TITLE_OPEN', 'Y'): ('qtitle', ('D', 'Y')),
        # ('qkurung', 'TITLE_CLOSE', 'D'): ('qhtml', 'epsilon'),

        # ('qkurung', 'LINK_OPEN', 'B'): ('qhtml', 'B'),
        # ('qkurung', 'LINK_OPEN', 'C'): ('qhtml', 'C'),
        # ('qkurung', 'LINK_OPEN', 'D'): ('qhtml', 'D'),
        # ('qkurung', 'LINK_OPEN', 'E'): ('qhtml', 'E'),
        # ('qkurung', 'LINK_OPEN', 'F'): ('qhtml', 'F'),
        # ('qkurung', 'LINK_OPEN', 'G'): ('qhtml', 'G'),
        # ('qkurung', 'LINK_OPEN', 'H'): ('qhtml', 'H'),
        # ('qkurung', 'LINK_OPEN', 'I'): ('qhtml', 'I'),
        # ('qkurung', 'LINK_OPEN', 'J'): ('qhtml', 'J'),
        # ('qkurung', 'LINK_OPEN', 'K'): ('qhtml', 'K'),
        # ('qkurung', 'LINK_OPEN', 'L'): ('qhtml', 'L'),
        # ('qkurung', 'LINK_OPEN', 'M'): ('qhtml', 'M'),
        # ('qkurung', 'LINK_OPEN', 'N'): ('qhtml', 'N'),
        # ('qkurung', 'LINK_OPEN', 'O'): ('qhtml', 'O'),
        # ('qkurung', 'LINK_OPEN', 'P'): ('qhtml', 'P'),
        # ('qkurung', 'LINK_OPEN', 'Q'): ('qhtml', 'Q'),
        # ('qkurung', 'LINK_OPEN', 'R'): ('qhtml', 'R'),
        # ('qkurung', 'LINK_OPEN', 'S'): ('qhtml', 'S'),
        # ('qkurung', 'LINK_OPEN', 'T'): ('qhtml', 'T'),
        # ('qkurung', 'LINK_OPEN', 'U'): ('qhtml', 'U'),
        # ('qkurung', 'LINK_OPEN', 'V'): ('qhtml', 'V'),
        # ('qkurung', 'LINK_OPEN', 'W'): ('qhtml', 'W'),
        # ('qkurung', 'LINK_OPEN', 'X'): ('qhtml', 'X'),
        # ('qkurung', 'LINK_OPEN', 'Y'): ('qhtml', 'Y'),

        # ('qhtml', 'IMG', 'C'): ('qimage', 'C'),
        # ('qhtml', 'IMG', 'E'): ('qimage', 'E'),
        # ('qhtml', 'IMG', 'F'): ('qimage', 'F'),
        # ('qhtml', 'IMG', 'G'): ('qimage', 'G'),
        # ('qhtml', 'IMG', 'H'): ('qimage', 'H'),
        # ('qhtml', 'IMG', 'I'): ('qimage', 'I'),
        # ('qhtml', 'IMG', 'J'): ('qimage', 'J'),
        # ('qhtml', 'IMG', 'K'): ('qimage', 'K'),
        # ('qhtml', 'IMG', 'L'): ('qimage', 'L'),
        # ('qhtml', 'IMG', 'M'): ('qimage', 'M'),
        # ('qhtml', 'IMG', 'N'): ('qimage', 'N'),
        # ('qhtml', 'IMG', 'O'): ('qimage', 'O'),
        # ('qhtml', 'IMG', 'P'): ('qimage', 'P'),
        # ('qhtml', 'IMG', 'Q'): ('qimage', 'Q'),
        # ('qhtml', 'IMG', 'R'): ('qimage', 'R'),
        # ('qhtml', 'IMG', 'S'): ('qimage', 'S'),
        # ('qhtml', 'IMG', 'T'): ('qimage', 'T'),
        # ('qhtml', 'IMG', 'U'): ('qimage', 'U'),
        # ('qhtml', 'IMG', 'V'): ('qimage', 'V'),
        # ('qhtml', 'IMG', 'W'): ('qimage', 'W'),
        # ('qhtml', 'IMG', 'X'): ('qimage', 'X'),
        # ('qhtml', 'IMG', 'Y'): ('qimage', 'Y'),

        # ('qimage', 'SRC', 'C'): ('qimage', ('d','C')),
        # ('qimage', 'SRC', 'E'): ('qimage', ('d','E')),
        # ('qimage', 'SRC', 'F'): ('qimage', ('d','F')),
        # ('qimage', 'SRC', 'G'): ('qimage', ('d','G')),
        # ('qimage', 'SRC', 'H'): ('qimage', ('d','H')),
        # ('qimage', 'SRC', 'I'): ('qimage', ('d','I')),
        # ('qimage', 'SRC', 'J'): ('qimage', ('d','J')),
        # ('qimage', 'SRC', 'K'): ('qimage', ('d','K')),
        # ('qimage', 'SRC', 'L'): ('qimage', ('d','L')),
        # ('qimage', 'SRC', 'M'): ('qimage', ('d','M')),
        # ('qimage', 'SRC', 'N'): ('qimage', ('d','N')),
        # ('qimage', 'SRC', 'O'): ('qimage', ('d','O')),
        # ('qimage', 'SRC', 'P'): ('qimage', ('d','P')),
        # ('qimage', 'SRC', 'Q'): ('qimage', ('d','Q')),
        # ('qimage', 'SRC', 'R'): ('qimage', ('d','R')),
        # ('qimage', 'SRC', 'S'): ('qimage', ('d','S')),
        # ('qimage', 'SRC', 'T'): ('qimage', ('d','T')),
        # ('qimage', 'SRC', 'U'): ('qimage', ('d','U')),
        # ('qimage', 'SRC', 'V'): ('qimage', ('d','V')),
        # ('qimage', 'SRC', 'W'): ('qimage', ('d','W')),
        # ('qimage', 'SRC', 'X'): ('qimage', ('d','X')),
        # ('qimage', 'SRC', 'Y'): ('qimage', ('d','Y')),
        # ('qimage', 'KURUNG_TUTUP', 'd'): ('qhtml', 'epsilon'),
        

 
        # ('qkurung', 'H1_OPEN', 'C'): ('qh1', ('F', 'C')),
        # ('qkurung', 'H1_OPEN', 'E'): ('qh1', ('F', 'E')),
        # ('qkurung', 'H1_OPEN', 'G'): ('qh1', ('F', 'G')),
        # ('qkurung', 'H1_OPEN', 'H'): ('qh1', ('F', 'H')),
        # ('qkurung', 'H1_OPEN', 'I'): ('qh1', ('F', 'I')),
        # ('qkurung', 'H1_OPEN', 'J'): ('qh1', ('F', 'J')),
        # ('qkurung', 'H1_OPEN', 'K'): ('qh1', ('F', 'K')),
        # ('qkurung', 'H1_OPEN', 'L'): ('qh1', ('F', 'L')),
        # ('qkurung', 'H1_OPEN', 'M'): ('qh1', ('F', 'M')),
        # ('qkurung', 'H1_OPEN', 'N'): ('qh1', ('F', 'N')),
        # ('qkurung', 'H1_OPEN', 'O'): ('qh1', ('F', 'O')),
        # ('qkurung', 'H1_OPEN', 'P'): ('qh1', ('F', 'P')),
        # ('qkurung', 'H1_OPEN', 'Q'): ('qh1', ('F', 'Q')),
        # ('qkurung', 'H1_OPEN', 'R'): ('qh1', ('F', 'R')),
        # ('qkurung', 'H1_OPEN', 'S'): ('qh1', ('F', 'S')),
        # ('qkurung', 'H1_OPEN', 'T'): ('qh1', ('F', 'T')),
        # ('qkurung', 'H1_OPEN', 'U'): ('qh1', ('F', 'U')),
        # ('qkurung', 'H1_OPEN', 'V'): ('qh1', ('F', 'V')),
        # ('qkurung', 'H1_OPEN', 'W'): ('qh1', ('F', 'W')),
        # ('qkurung', 'H1_OPEN', 'X'): ('qh1', ('F', 'X')),
        # ('qkurung', 'H1_OPEN', 'Y'): ('qh1', ('F', 'Y')),
        # ('qkurung', 'H1_CLOSE', 'F'): ('qh1', 'epsilon'),

        # ('qkurung', 'H2_OPEN', 'C'): ('qh2', ('G', 'C')),
        # ('qkurung', 'H2_OPEN', 'E'): ('qh2', ('G', 'E')),
        # ('qkurung', 'H2_OPEN', 'F'): ('qh2', ('G', 'F')),
        # ('qkurung', 'H2_OPEN', 'H'): ('qh2', ('G', 'H')),
        # ('qkurung', 'H2_OPEN', 'I'): ('qh2', ('G', 'I')),
        # ('qkurung', 'H2_OPEN', 'J'): ('qh2', ('G', 'J')),
        # ('qkurung', 'H2_OPEN', 'K'): ('qh2', ('G', 'K')),
        # ('qkurung', 'H2_OPEN', 'L'): ('qh2', ('G', 'L')),
        # ('qkurung', 'H2_OPEN', 'M'): ('qh2', ('G', 'M')),
        # ('qkurung', 'H2_OPEN', 'N'): ('qh2', ('G', 'N')),
        # ('qkurung', 'H2_OPEN', 'O'): ('qh2', ('G', 'O')),
        # ('qkurung', 'H2_OPEN', 'P'): ('qh2', ('G', 'P')),
        # ('qkurung', 'H2_OPEN', 'Q'): ('qh2', ('G', 'Q')),
        # ('qkurung', 'H2_OPEN', 'R'): ('qh2', ('G', 'R')),
        # ('qkurung', 'H2_OPEN', 'S'): ('qh2', ('G', 'S')),
        # ('qkurung', 'H2_OPEN', 'T'): ('qh2', ('G', 'T')),
        # ('qkurung', 'H2_OPEN', 'U'): ('qh2', ('G', 'U')),
        # ('qkurung', 'H2_OPEN', 'V'): ('qh2', ('G', 'V')),
        # ('qkurung', 'H2_OPEN', 'W'): ('qh2', ('G', 'W')),
        # ('qkurung', 'H2_OPEN', 'X'): ('qh2', ('G', 'X')),
        # ('qkurung', 'H2_OPEN', 'Y'): ('qh2', ('G', 'Y')),
        # ('qkurung', 'H2_CLOSE', 'F'): ('qkurung', 'epsilon'),

        # ('qkurung', 'H3_OPEN', 'C'): ('qh3', ('H', 'C')),
        # ('qkurung', 'H3_OPEN', 'E'): ('qh3', ('H', 'E')),
        # ('qkurung', 'H3_OPEN', 'F'): ('qh3', ('H', 'F')),
        # ('qkurung', 'H3_OPEN', 'G'): ('qh3', ('H', 'G')),
        # ('qkurung', 'H3_OPEN', 'I'): ('qh3', ('H', 'I')),
        # ('qkurung', 'H3_OPEN', 'J'): ('qh3', ('H', 'J')),
        # ('qkurung', 'H3_OPEN', 'K'): ('qh3', ('H', 'K')),
        # ('qkurung', 'H3_OPEN', 'L'): ('qh3', ('H', 'L')),
        # ('qkurung', 'H3_OPEN', 'M'): ('qh3', ('H', 'M')),
        # ('qkurung', 'H3_OPEN', 'N'): ('qh3', ('H', 'N')),
        # ('qkurung', 'H3_OPEN', 'O'): ('qh3', ('H', 'O')),
        # ('qkurung', 'H3_OPEN', 'P'): ('qh3', ('H', 'P')),
        # ('qkurung', 'H3_OPEN', 'Q'): ('qh3', ('H', 'Q')),
        # ('qkurung', 'H3_OPEN', 'R'): ('qh3', ('H', 'R')),
        # ('qkurung', 'H3_OPEN', 'S'): ('qh3', ('H', 'S')),
        # ('qkurung', 'H3_OPEN', 'T'): ('qh3', ('H', 'T')),
        # ('qkurung', 'H3_OPEN', 'U'): ('qh3', ('H', 'U')),
        # ('qkurung', 'H3_OPEN', 'V'): ('qh3', ('H', 'V')),
        # ('qkurung', 'H3_OPEN', 'W'): ('qh3', ('H', 'W')),
        # ('qkurung', 'H3_OPEN', 'X'): ('qh3', ('H', 'X')),
        # ('qkurung', 'H3_OPEN', 'Y'): ('qh3', ('H', 'Y')),
        # ('qkurung', 'H3_CLOSE', 'F'): ('qkurung', 'epsilon'),
        
        # ('qkurung', 'H4_OPEN', 'C'): ('qh4', ('I', 'C')),
        # ('qkurung', 'H4_OPEN', 'E'): ('qh4', ('I', 'E')),
        # ('qkurung', 'H4_OPEN', 'F'): ('qh4', ('I', 'F')),
        # ('qkurung', 'H4_OPEN', 'G'): ('qh4', ('I', 'G')),
        # ('qkurung', 'H4_OPEN', 'H'): ('qh4', ('I', 'H')),
        # ('qkurung', 'H4_OPEN', 'J'): ('qh4', ('I', 'J')),
        # ('qkurung', 'H4_OPEN', 'K'): ('qh4', ('I', 'K')),
        # ('qkurung', 'H4_OPEN', 'L'): ('qh4', ('I', 'L')),
        # ('qkurung', 'H4_OPEN', 'M'): ('qh4', ('I', 'M')),
        # ('qkurung', 'H4_OPEN', 'N'): ('qh4', ('I', 'N')),
        # ('qkurung', 'H4_OPEN', 'O'): ('qh4', ('I', 'O')),
        # ('qkurung', 'H4_OPEN', 'P'): ('qh4', ('I', 'P')),
        # ('qkurung', 'H4_OPEN', 'Q'): ('qh4', ('I', 'Q')),
        # ('qkurung', 'H4_OPEN', 'R'): ('qh4', ('I', 'R')),
        # ('qkurung', 'H4_OPEN', 'S'): ('qh4', ('I', 'S')),
        # ('qkurung', 'H4_OPEN', 'T'): ('qh4', ('I', 'T')),
        # ('qkurung', 'H4_OPEN', 'U'): ('qh4', ('I', 'U')),
        # ('qkurung', 'H4_OPEN', 'V'): ('qh4', ('I', 'V')),
        # ('qkurung', 'H4_OPEN', 'W'): ('qh4', ('I', 'W')),
        # ('qkurung', 'H4_OPEN', 'X'): ('qh4', ('I', 'X')),
        # ('qkurung', 'H4_OPEN', 'Y'): ('qh4', ('I', 'Y')),
        # ('qkurung', 'H4_CLOSE', 'F'): ('qkurung', 'epsilon'),
        
        # ('qkurung', 'H5_OPEN', 'C'): ('qh5', ('J', 'C')),
        # ('qkurung', 'H5_OPEN', 'E'): ('qh5', ('J', 'E')),
        # ('qkurung', 'H5_OPEN', 'F'): ('qh5', ('J', 'F')),
        # ('qkurung', 'H5_OPEN', 'G'): ('qh5', ('J', 'G')),
        # ('qkurung', 'H5_OPEN', 'H'): ('qh5', ('J', 'H')),
        # ('qkurung', 'H5_OPEN', 'I'): ('qh5', ('J', 'I')),
        # ('qkurung', 'H5_OPEN', 'K'): ('qh5', ('J', 'K')),
        # ('qkurung', 'H5_OPEN', 'L'): ('qh5', ('J', 'L')),
        # ('qkurung', 'H5_OPEN', 'M'): ('qh5', ('J', 'M')),
        # ('qkurung', 'H5_OPEN', 'N'): ('qh5', ('J', 'N')),
        # ('qkurung', 'H5_OPEN', 'O'): ('qh5', ('J', 'O')),
        # ('qkurung', 'H5_OPEN', 'P'): ('qh5', ('J', 'P')),
        # ('qkurung', 'H5_OPEN', 'Q'): ('qh5', ('J', 'Q')),
        # ('qkurung', 'H5_OPEN', 'R'): ('qh5', ('J', 'R')),
        # ('qkurung', 'H5_OPEN', 'S'): ('qh5', ('J', 'S')),
        # ('qkurung', 'H5_OPEN', 'T'): ('qh5', ('J', 'T')),
        # ('qkurung', 'H5_OPEN', 'U'): ('qh5', ('J', 'U')),
        # ('qkurung', 'H5_OPEN', 'V'): ('qh5', ('J', 'V')),
        # ('qkurung', 'H5_OPEN', 'W'): ('qh5', ('J', 'W')),
        # ('qkurung', 'H5_OPEN', 'X'): ('qh5', ('J', 'X')),
        # ('qkurung', 'H5_OPEN', 'Y'): ('qh5', ('J', 'Y')),
        # ('qkurung', 'H5_CLOSE', 'F'): ('qkurung', 'epsilon'),

        # ('qkurung', 'H6_OPEN', 'C'): ('qh6', ('K', 'C')),
        # ('qkurung', 'H6_OPEN', 'E'): ('qh6', ('K', 'E')),
        # ('qkurung', 'H6_OPEN', 'F'): ('qh6', ('K', 'F')),
        # ('qkurung', 'H6_OPEN', 'G'): ('qh6', ('K', 'G')),
        # ('qkurung', 'H6_OPEN', 'H'): ('qh6', ('K', 'H')),
        # ('qkurung', 'H6_OPEN', 'I'): ('qh6', ('K', 'I')),
        # ('qkurung', 'H6_OPEN', 'J'): ('qh6', ('K', 'J')),
        # ('qkurung', 'H6_OPEN', 'L'): ('qh6', ('K', 'L')),
        # ('qkurung', 'H6_OPEN', 'M'): ('qh6', ('K', 'M')),
        # ('qkurung', 'H6_OPEN', 'N'): ('qh6', ('K', 'N')),
        # ('qkurung', 'H6_OPEN', 'O'): ('qh6', ('K', 'O')),
        # ('qkurung', 'H6_OPEN', 'P'): ('qh6', ('K', 'P')),
        # ('qkurung', 'H6_OPEN', 'Q'): ('qh6', ('K', 'Q')),
        # ('qkurung', 'H6_OPEN', 'R'): ('qh6', ('K', 'R')),
        # ('qkurung', 'H6_OPEN', 'S'): ('qh6', ('K', 'S')),
        # ('qkurung', 'H6_OPEN', 'T'): ('qh6', ('K', 'T')),
        # ('qkurung', 'H6_OPEN', 'U'): ('qh6', ('K', 'U')),
        # ('qkurung', 'H6_OPEN', 'V'): ('qh6', ('K', 'V')),
        # ('qkurung', 'H6_OPEN', 'W'): ('qh6', ('K', 'W')),
        # ('qkurung', 'H6_OPEN', 'X'): ('qh6', ('K', 'X')),
        # ('qkurung', 'H6_OPEN', 'Y'): ('qh6', ('K', 'Y')),
        # ('qkurung', 'H6_CLOSE', 'F'): ('qkurung', 'epsilon'),

        # ('qkurung', 'P_OPEN', 'C'): ('qp', ('L', 'C')),
        # ('qkurung', 'P_OPEN', 'E'): ('qp', ('L', 'E')),
        # ('qkurung', 'P_OPEN', 'F'): ('qp', ('L', 'F')),
        # ('qkurung', 'P_OPEN', 'G'): ('qp', ('L', 'G')),
        # ('qkurung', 'P_OPEN', 'H'): ('qp', ('L', 'H')),
        # ('qkurung', 'P_OPEN', 'I'): ('qp', ('L', 'I')),
        # ('qkurung', 'P_OPEN', 'J'): ('qp', ('L', 'J')),
        # ('qkurung', 'P_OPEN', 'K'): ('qp', ('L', 'K')),
        # ('qkurung', 'P_OPEN', 'M'): ('qp', ('L', 'M')),
        # ('qkurung', 'P_OPEN', 'N'): ('qp', ('L', 'N')),
        # ('qkurung', 'P_OPEN', 'O'): ('qp', ('L', 'O')),
        # ('qkurung', 'P_OPEN', 'P'): ('qp', ('L', 'P')),
        # ('qkurung', 'P_OPEN', 'Q'): ('qp', ('L', 'Q')),
        # ('qkurung', 'P_OPEN', 'R'): ('qp', ('L', 'R')),
        # ('qkurung', 'P_OPEN', 'S'): ('qp', ('L', 'S')),
        # ('qkurung', 'P_OPEN', 'T'): ('qp', ('L', 'T')),
        # ('qkurung', 'P_OPEN', 'U'): ('qp', ('L', 'U')),
        # ('qkurung', 'P_OPEN', 'V'): ('qp', ('L', 'V')),
        # ('qkurung', 'P_OPEN', 'W'): ('qp', ('L', 'W')),
        # ('qkurung', 'P_OPEN', 'X'): ('qp', ('L', 'X')),
        # ('qkurung', 'P_OPEN', 'Y'): ('qp', ('L', 'Y')),
        # ('qkurung', 'P_CLOSE', 'F'): ('qkurung', 'epsilon'),
      
        # ('qkurung', 'EM_OPEN', 'C'): ('qem', ('M', 'C')),
        # ('qkurung', 'EM_OPEN', 'E'): ('qem', ('M', 'E')),
        # ('qkurung', 'EM_OPEN', 'F'): ('qem', ('M', 'F')),
        # ('qkurung', 'EM_OPEN', 'G'): ('qem', ('M', 'G')),
        # ('qkurung', 'EM_OPEN', 'H'): ('qem', ('M', 'H')),
        # ('qkurung', 'EM_OPEN', 'I'): ('qem', ('M', 'I')),
        # ('qkurung', 'EM_OPEN', 'J'): ('qem', ('M', 'J')),
        # ('qkurung', 'EM_OPEN', 'K'): ('qem', ('M', 'K')),
        # ('qkurung', 'EM_OPEN', 'M'): ('qem', ('M', 'M')),
        # ('qkurung', 'EM_OPEN', 'N'): ('qem', ('M', 'N')),
        # ('qkurung', 'EM_OPEN', 'O'): ('qem', ('M', 'O')),
        # ('qkurung', 'EM_OPEN', 'P'): ('qem', ('M', 'P')),
        # ('qkurung', 'EM_OPEN', 'Q'): ('qem', ('M', 'Q')),
        # ('qkurung', 'EM_OPEN', 'R'): ('qem', ('M', 'R')),
        # ('qkurung', 'EM_OPEN', 'S'): ('qem', ('M', 'S')),
        # ('qkurung', 'EM_OPEN', 'T'): ('qem', ('M', 'T')),
        # ('qkurung', 'EM_OPEN', 'U'): ('qem', ('M', 'U')),
        # ('qkurung', 'EM_OPEN', 'V'): ('qem', ('M', 'V')),
        # ('qkurung', 'EM_OPEN', 'W'): ('qem', ('M', 'W')),
        # ('qkurung', 'EM_OPEN', 'X'): ('qem', ('M', 'X')),
        # ('qkurung', 'EM_OPEN', 'Y'): ('qem', ('M', 'Y')),
        # ('qkurung', 'EM_CLOSE', 'F'): ('qkurung', 'epsilon'),
  
        # ('qkurung', 'A_OPEN', 'C'): ('qa', ('S', 'C')),
        # ('qkurung', 'A_OPEN', 'E'): ('qa', ('S', 'E')),
        # ('qkurung', 'A_OPEN', 'F'): ('qa', ('S', 'F')),
        # ('qkurung', 'A_OPEN', 'G'): ('qa', ('S', 'G')),
        # ('qkurung', 'A_OPEN', 'H'): ('qa', ('S', 'H')),
        # ('qkurung', 'A_OPEN', 'I'): ('qa', ('S', 'I')),
        # ('qkurung', 'A_OPEN', 'J'): ('qa', ('S', 'J')),
        # ('qkurung', 'A_OPEN', 'K'): ('qa', ('S', 'K')),
        # ('qkurung', 'A_OPEN', 'L'): ('qa', ('S', 'L')),
        # ('qkurung', 'A_OPEN', 'M'): ('qa', ('S', 'M')),
        # ('qkurung', 'A_OPEN', 'N'): ('qa', ('S', 'N')),
        # ('qkurung', 'A_OPEN', 'O'): ('qa', ('S', 'O')),
        # ('qkurung', 'A_OPEN', 'P'): ('qa', ('S', 'P')),
        # ('qkurung', 'A_OPEN', 'Q'): ('qa', ('S', 'Q')),
        # ('qkurung', 'A_OPEN', 'R'): ('qa', ('S', 'R')),
        # ('qkurung', 'A_OPEN', 'S'): ('qa', ('S', 'S')),
        # ('qkurung', 'A_OPEN', 'T'): ('qa', ('S', 'T')),
        # ('qkurung', 'A_OPEN', 'U'): ('qa', ('S', 'U')),
        # ('qkurung', 'A_OPEN', 'V'): ('qa', ('S', 'V')),
        # ('qkurung', 'A_OPEN', 'W'): ('qa', ('S', 'W')),
        # ('qkurung', 'A_OPEN', 'X'): ('qa', ('S', 'X')),
        # ('qkurung', 'A_OPEN', 'Y'): ('qa', ('S', 'Y')),
        # ('qkurung', 'A_CLOSE', 'S'): ('qkurung', 'epsilon'),

        # ('qkurung', 'B_OPEN', 'C'): ('qb', ('N', 'C')),
        # ('qkurung', 'B_OPEN', 'E'): ('qb', ('N', 'E')),
        # ('qkurung', 'B_OPEN', 'F'): ('qb', ('N', 'F')),
        # ('qkurung', 'B_OPEN', 'G'): ('qb', ('N', 'G')),
        # ('qkurung', 'B_OPEN', 'H'): ('qb', ('N', 'H')),
        # ('qkurung', 'B_OPEN', 'I'): ('qb', ('N', 'I')),
        # ('qkurung', 'B_OPEN', 'J'): ('qb', ('N', 'J')),
        # ('qkurung', 'B_OPEN', 'K'): ('qb', ('N', 'K')),
        # ('qkurung', 'B_OPEN', 'L'): ('qb', ('N', 'L')),
        # ('qkurung', 'B_OPEN', 'M'): ('qb', ('N', 'M')),
        # ('qkurung', 'B_OPEN', 'O'): ('qb', ('N', 'O')),
        # ('qkurung', 'B_OPEN', 'P'): ('qb', ('N', 'P')),
        # ('qkurung', 'B_OPEN', 'Q'): ('qb', ('N', 'Q')),
        # ('qkurung', 'B_OPEN', 'R'): ('qb', ('N', 'R')),
        # ('qkurung', 'B_OPEN', 'S'): ('qb', ('N', 'S')),
        # ('qkurung', 'B_OPEN', 'T'): ('qb', ('N', 'T')),
        # ('qkurung', 'B_OPEN', 'U'): ('qb', ('N', 'U')),
        # ('qkurung', 'B_OPEN', 'V'): ('qb', ('N', 'V')),
        # ('qkurung', 'B_OPEN', 'W'): ('qb', ('N', 'W')),
        # ('qkurung', 'B_OPEN', 'X'): ('qb', ('N', 'X')),
        # ('qkurung', 'B_OPEN', 'Y'): ('qb', ('N', 'Y')),
        # ('qkurung', 'B_CLOSE', 'N'): ('qkurung', 'epsilon'),
    
        # ('qkurung', 'ABBR_OPEN', 'C'): ('qabbr', ('O', 'C')),
        # ('qkurung', 'ABBR_OPEN', 'E'): ('qabbr', ('O', 'E')),
        # ('qkurung', 'ABBR_OPEN', 'F'): ('qabbr', ('O', 'F')),
        # ('qkurung', 'ABBR_OPEN', 'G'): ('qabbr', ('O', 'G')),
        # ('qkurung', 'ABBR_OPEN', 'H'): ('qabbr', ('O', 'H')),
        # ('qkurung', 'ABBR_OPEN', 'I'): ('qabbr', ('O', 'I')),
        # ('qkurung', 'ABBR_OPEN', 'J'): ('qabbr', ('O', 'J')),
        # ('qkurung', 'ABBR_OPEN', 'K'): ('qabbr', ('O', 'K')),
        # ('qkurung', 'ABBR_OPEN', 'L'): ('qabbr', ('O', 'L')),
        # ('qkurung', 'ABBR_OPEN', 'M'): ('qabbr', ('O', 'M')),
        # ('qkurung', 'ABBR_OPEN', 'N'): ('qabbr', ('O', 'N')),
        # ('qkurung', 'ABBR_OPEN', 'P'): ('qabbr', ('O', 'P')),
        # ('qkurung', 'ABBR_OPEN', 'Q'): ('qabbr', ('O', 'Q')),
        # ('qkurung', 'ABBR_OPEN', 'R'): ('qabbr', ('O', 'R')),
        # ('qkurung', 'ABBR_OPEN', 'S'): ('qabbr', ('O', 'S')),
        # ('qkurung', 'ABBR_OPEN', 'T'): ('qabbr', ('O', 'T')),
        # ('qkurung', 'ABBR_OPEN', 'U'): ('qabbr', ('O', 'U')),
        # ('qkurung', 'ABBR_OPEN', 'V'): ('qabbr', ('O', 'V')),
        # ('qkurung', 'ABBR_OPEN', 'W'): ('qabbr', ('O', 'W')),
        # ('qkurung', 'ABBR_OPEN', 'X'): ('qabbr', ('O', 'X')),
        # ('qkurung', 'ABBR_OPEN', 'Y'): ('qabbr', ('O', 'Y')),
        # ('qkurung', 'ABBR_CLOSE', 'O'): ('qkurung', 'epsilon'),

        # ('qkurung', 'STRONG_OPEN', 'C'): ('qstrong', ('P', 'C')),
        # ('qkurung', 'STRONG_OPEN', 'E'): ('qstrong', ('P', 'E')),
        # ('qkurung', 'STRONG_OPEN', 'F'): ('qstrong', ('P', 'F')),
        # ('qkurung', 'STRONG_OPEN', 'G'): ('qstrong', ('P', 'G')),
        # ('qkurung', 'STRONG_OPEN', 'H'): ('qstrong', ('P', 'H')),
        # ('qkurung', 'STRONG_OPEN', 'I'): ('qstrong', ('P', 'I')),
        # ('qkurung', 'STRONG_OPEN', 'J'): ('qstrong', ('P', 'J')),
        # ('qkurung', 'STRONG_OPEN', 'K'): ('qstrong', ('P', 'K')),
        # ('qkurung', 'STRONG_OPEN', 'L'): ('qstrong', ('P', 'L')),
        # ('qkurung', 'STRONG_OPEN', 'M'): ('qstrong', ('P', 'M')),
        # ('qkurung', 'STRONG_OPEN', 'N'): ('qstrong', ('P', 'N')),
        # ('qkurung', 'STRONG_OPEN', 'O'): ('qstrong', ('P', 'O')),
        # ('qkurung', 'STRONG_OPEN', 'Q'): ('qstrong', ('P', 'Q')),
        # ('qkurung', 'STRONG_OPEN', 'R'): ('qstrong', ('P', 'R')),
        # ('qkurung', 'STRONG_OPEN', 'S'): ('qstrong', ('P', 'S')),
        # ('qkurung', 'STRONG_OPEN', 'T'): ('qstrong', ('P', 'T')),
        # ('qkurung', 'STRONG_OPEN', 'U'): ('qstrong', ('P', 'U')),
        # ('qkurung', 'STRONG_OPEN', 'V'): ('qstrong', ('P', 'V')),
        # ('qkurung', 'STRONG_OPEN', 'W'): ('qstrong', ('P', 'W')),
        # ('qkurung', 'STRONG_OPEN', 'X'): ('qstrong', ('P', 'X')),
        # ('qkurung', 'STRONG_OPEN', 'Y'): ('qstrong', ('P', 'Y')),
        # ('qkurung', 'STRONG_CLOSE', 'P'): ('qkurung', 'epsilon'),

        # ('qkurung', 'SMALL_OPEN', 'C'): ('qsmall', ('Q', 'C')),
        # ('qkurung', 'SMALL_OPEN', 'E'): ('qsmall', ('Q', 'E')),
        # ('qkurung', 'SMALL_OPEN', 'F'): ('qsmall', ('Q', 'F')),
        # ('qkurung', 'SMALL_OPEN', 'G'): ('qsmall', ('Q', 'G')),
        # ('qkurung', 'SMALL_OPEN', 'H'): ('qsmall', ('Q', 'H')),
        # ('qkurung', 'SMALL_OPEN', 'I'): ('qsmall', ('Q', 'I')),
        # ('qkurung', 'SMALL_OPEN', 'J'): ('qsmall', ('Q', 'J')),
        # ('qkurung', 'SMALL_OPEN', 'K'): ('qsmall', ('Q', 'K')),
        # ('qkurung', 'SMALL_OPEN', 'L'): ('qsmall', ('Q', 'L')),
        # ('qkurung', 'SMALL_OPEN', 'M'): ('qsmall', ('Q', 'M')),
        # ('qkurung', 'SMALL_OPEN', 'N'): ('qsmall', ('Q', 'N')),
        # ('qkurung', 'SMALL_OPEN', 'O'): ('qsmall', ('Q', 'O')),
        # ('qkurung', 'SMALL_OPEN', 'P'): ('qsmall', ('Q', 'P')),
        # ('qkurung', 'SMALL_OPEN', 'R'): ('qsmall', ('Q', 'R')),
        # ('qkurung', 'SMALL_OPEN', 'S'): ('qsmall', ('Q', 'S')),
        # ('qkurung', 'SMALL_OPEN', 'T'): ('qsmall', ('Q', 'T')),
        # ('qkurung', 'SMALL_OPEN', 'U'): ('qsmall', ('Q', 'U')),
        # ('qkurung', 'SMALL_OPEN', 'V'): ('qsmall', ('Q', 'V')),
        # ('qkurung', 'SMALL_OPEN', 'W'): ('qsmall', ('Q', 'W')),
        # ('qkurung', 'SMALL_OPEN', 'X'): ('qsmall', ('Q', 'X')),
        # ('qkurung', 'SMALL_OPEN', 'Y'): ('qsmall', ('Q', 'Y')),
        # ('qkurung', 'SMALL_CLOSE', 'Q'): ('qkurung', 'epsilon'),

        # ('qkurung', 'HR_OPEN', 'B'): ('qkurung', 'B'),
        # ('qkurung', 'HR_OPEN', 'C'): ('qkurung', 'C'),
        # ('qkurung', 'HR_OPEN', 'D'): ('qkurung', 'D'),
        # ('qkurung', 'HR_OPEN', 'E'): ('qkurung', 'E'),
        # ('qkurung', 'HR_OPEN', 'F'): ('qkurung', 'F'),
        # ('qkurung', 'HR_OPEN', 'G'): ('qkurung', 'G'),
        # ('qkurung', 'HR_OPEN', 'H'): ('qkurung', 'H'),
        # ('qkurung', 'HR_OPEN', 'I'): ('qkurung', 'I'),
        # ('qkurung', 'HR_OPEN', 'J'): ('qkurung', 'J'),
        # ('qkurung', 'HR_OPEN', 'K'): ('qkurung', 'K'),
        # ('qkurung', 'HR_OPEN', 'L'): ('qkurung', 'L'),
        # ('qkurung', 'HR_OPEN', 'M'): ('qkurung', 'M'),
        # ('qkurung', 'HR_OPEN', 'N'): ('qkurung', 'N'),
        # ('qkurung', 'HR_OPEN', 'O'): ('qkurung', 'O'),
        # ('qkurung', 'HR_OPEN', 'P'): ('qkurung', 'P'),
        # ('qkurung', 'HR_OPEN', 'Q'): ('qkurung', 'Q'),
        # ('qkurung', 'HR_OPEN', 'R'): ('qkurung', 'R'),
        # ('qkurung', 'HR_OPEN', 'S'): ('qkurung', 'S'),
        # ('qkurung', 'HR_OPEN', 'T'): ('qkurung', 'T'),
        # ('qkurung', 'HR_OPEN', 'U'): ('qkurung', 'U'),
        # ('qkurung', 'HR_OPEN', 'V'): ('qkurung', 'V'),
        # ('qkurung', 'HR_OPEN', 'W'): ('qkurung', 'W'),
        # ('qkurung', 'HR_OPEN', 'X'): ('qkurung', 'X'),
        # ('qkurung', 'HR_OPEN', 'Y'): ('qkurung', 'Y'),
        
        # ('qkurung', 'BR', 'B'): ('qkurung', ('b','B')),
        # ('qkurung', 'BR', 'C'): ('qkurung', ('b','C')),
        # ('qkurung', 'BR', 'D'): ('qkurung', ('b','D')),
        # ('qkurung', 'BR', 'E'): ('qkurung', ('b','E')),
        # ('qkurung', 'BR', 'F'): ('qkurung', ('b','F')),
        # ('qkurung', 'BR', 'G'): ('qkurung', ('b','G')),
        # ('qkurung', 'BR', 'H'): ('qkurung', ('b','H')),
        # ('qkurung', 'BR', 'I'): ('qkurung', ('b','I')),
        # ('qkurung', 'BR', 'J'): ('qkurung', ('b','J')),
        # ('qkurung', 'BR', 'K'): ('qkurung', ('b','K')),
        # ('qkurung', 'BR', 'L'): ('qkurung', ('b','L')),
        # ('qkurung', 'BR', 'M'): ('qkurung', ('b','M')),
        # ('qkurung', 'BR', 'N'): ('qkurung', ('b','N')),
        # ('qkurung', 'BR', 'O'): ('qkurung', ('b','O')),
        # ('qkurung', 'BR', 'P'): ('qkurung', ('b','P')),
        # ('qkurung', 'BR', 'Q'): ('qkurung', ('b','Q')),
        # ('qkurung', 'BR', 'R'): ('qkurung', ('b','R')),
        # ('qkurung', 'BR', 'S'): ('qkurung', ('b','S')),
        # ('qkurung', 'BR', 'T'): ('qkurung', ('b','T')),
        # ('qkurung', 'BR', 'U'): ('qkurung', ('b','U')),
        # ('qkurung', 'BR', 'V'): ('qkurung', ('b','V')),
        # ('qkurung', 'BR', 'W'): ('qkurung', ('b','W')),
        # ('qkurung', 'BR', 'X'): ('qkurung', ('b','X')),
        # ('qkurung', 'BR', 'Y'): ('qkurung', ('b','Y')),
        # ('qkurung', 'BR', 'b'): ('qkurung', 'epsilon'),


        # ('qkurung', 'DIV_OPEN', 'C'): ('qdiv', ('R', 'C')),
        # ('qkurung', 'DIV_OPEN', 'E'): ('qdiv', ('R', 'E')),
        # ('qkurung', 'DIV_OPEN', 'F'): ('qdiv', ('R', 'F')),
        # ('qkurung', 'DIV_OPEN', 'G'): ('qdiv', ('R', 'G')),
        # ('qkurung', 'DIV_OPEN', 'H'): ('qdiv', ('R', 'H')),
        # ('qkurung', 'DIV_OPEN', 'I'): ('qdiv', ('R', 'I')),
        # ('qkurung', 'DIV_OPEN', 'J'): ('qdiv', ('R', 'J')),
        # ('qkurung', 'DIV_OPEN', 'K'): ('qdiv', ('R', 'K')),
        # ('qkurung', 'DIV_OPEN', 'L'): ('qdiv', ('R', 'L')),
        # ('qkurung', 'DIV_OPEN', 'M'): ('qdiv', ('R', 'M')),
        # ('qkurung', 'DIV_OPEN', 'N'): ('qdiv', ('R', 'N')),
        # ('qkurung', 'DIV_OPEN', 'O'): ('qdiv', ('R', 'O')),
        # ('qkurung', 'DIV_OPEN', 'P'): ('qdiv', ('R', 'P')),
        # ('qkurung', 'DIV_OPEN', 'Q'): ('qdiv', ('Q', 'R')),
        # ('qkurung', 'DIV_OPEN', 'S'): ('qdiv', ('R', 'S')),
        # ('qkurung', 'DIV_OPEN', 'T'): ('qdiv', ('R', 'T')),
        # ('qkurung', 'DIV_OPEN', 'U'): ('qdiv', ('R', 'U')),
        # ('qkurung', 'DIV_OPEN', 'V'): ('qdiv', ('R', 'V')),
        # ('qkurung', 'DIV_OPEN', 'W'): ('qdiv', ('R', 'W')),
        # ('qkurung', 'DIV_OPEN', 'X'): ('qdiv', ('R', 'X')),
        # ('qkurung', 'DIV_OPEN', 'Y'): ('qdiv', ('R', 'Y')),
        # ('qkurung', 'DIV_CLOSE', 'R'): ('qkurung', 'epsilon'),
     
      
    
        # ('qkurung', 'BUTTON_OPEN', 'C'): ('qbutton', ('T', 'C')),
        # ('qkurung', 'BUTTON_OPEN', 'E'): ('qbutton', ('T', 'E')),
        # ('qkurung', 'BUTTON_OPEN', 'F'): ('qbutton', ('T', 'F')),
        # ('qkurung', 'BUTTON_OPEN', 'G'): ('qbutton', ('T', 'G')),
        # ('qkurung', 'BUTTON_OPEN', 'H'): ('qbutton', ('T', 'H')),
        # ('qkurung', 'BUTTON_OPEN', 'I'): ('qbutton', ('T', 'I')),
        # ('qkurung', 'BUTTON_OPEN', 'J'): ('qbutton', ('T', 'J')),
        # ('qkurung', 'BUTTON_OPEN', 'K'): ('qbutton', ('T', 'K')),
        # ('qkurung', 'BUTTON_OPEN', 'L'): ('qbutton', ('T', 'L')),
        # ('qkurung', 'BUTTON_OPEN', 'M'): ('qbutton', ('T', 'M')),
        # ('qkurung', 'BUTTON_OPEN', 'N'): ('qbutton', 'T'),
        # ('qkurung', 'BUTTON_OPEN', 'O'): ('qbutton', ('T', 'O')),
        # ('qkurung', 'BUTTON_OPEN', 'P'): ('qbutton', ('T', 'P')),
        # ('qkurung', 'BUTTON_OPEN', 'Q'): ('qbutton', ('T', 'Q')),
        # ('qkurung', 'BUTTON_OPEN', 'R'): ('qbutton', ('T', 'R')),
        # ('qkurung', 'BUTTON_OPEN', 'S'): ('qbutton', ('T', 'S')),
        # ('qkurung', 'BUTTON_OPEN', 'U'): ('qbutton', ('T', 'U')),
        # ('qkurung', 'BUTTON_OPEN', 'V'): ('qbutton', ('T', 'V')),
        # ('qkurung', 'BUTTON_OPEN', 'W'): ('qbutton', ('T', 'W')),
        # ('qkurung', 'BUTTON_OPEN', 'X'): ('qbutton', ('T', 'X')),
        # ('qkurung', 'BUTTON_OPEN', 'Y'): ('qbutton', ('T', 'Y')),
        # ('qkurung', 'BUTTON_CLOSE', 'T'): ('qkurung', 'epsilon'),
    
        # ('qkurung', 'FORM_OPEN', 'C'): ('qform', ('U', 'C')),
        # ('qkurung', 'FORM_OPEN', 'E'): ('qform', ('U', 'E')),
        # ('qkurung', 'FORM_OPEN', 'F'): ('qform', ('U', 'F')),
        # ('qkurung', 'FORM_OPEN', 'G'): ('qform', ('U', 'G')),
        # ('qkurung', 'FORM_OPEN', 'H'): ('qform', ('U', 'H')),
        # ('qkurung', 'FORM_OPEN', 'I'): ('qform', ('U', 'I')),
        # ('qkurung', 'FORM_OPEN', 'J'): ('qform', ('U', 'J')),
        # ('qkurung', 'FORM_OPEN', 'K'): ('qform', ('U', 'K')),
        # ('qkurung', 'FORM_OPEN', 'L'): ('qform', ('U', 'L')),
        # ('qkurung', 'FORM_OPEN', 'M'): ('qform', ('U', 'M')),
        # ('qkurung', 'FORM_OPEN', 'N'): ('qform', ('U', 'N')),
        # ('qkurung', 'FORM_OPEN', 'O'): ('qform', ('U', 'O')),
        # ('qkurung', 'FORM_OPEN', 'P'): ('qform', ('U', 'P')),
        # ('qkurung', 'FORM_OPEN', 'Q'): ('qform', ('U', 'Q')),
        # ('qkurung', 'FORM_OPEN', 'R'): ('qform', ('U', 'R')),
        # ('qkurung', 'FORM_OPEN', 'S'): ('qform', ('U', 'S')),
        # ('qkurung', 'FORM_OPEN', 'T'): ('qform', ('U', 'T')),
        # ('qkurung', 'FORM_OPEN', 'V'): ('qform', ('U', 'V')),
        # ('qkurung', 'FORM_OPEN', 'W'): ('qform', ('U', 'W')),
        # ('qkurung', 'FORM_OPEN', 'X'): ('qform', ('U', 'X')),
        # ('qkurung', 'FORM_OPEN', 'Y'): ('qform', ('U', 'Y')),
        # ('qkurung', 'FORM_CLOSE', 'U'): ('qkurung', 'epsilon'),

        # ('qkurung', 'TABLE_OPEN', 'C'): ('qtable', ('V', 'C')),
        # ('qkurung', 'TABLE_OPEN', 'E'): ('qtable', ('V', 'E')),
        # ('qkurung', 'TABLE_OPEN', 'F'): ('qtable', ('V', 'F')),
        # ('qkurung', 'TABLE_OPEN', 'G'): ('qtable', ('V', 'G')),
        # ('qkurung', 'TABLE_OPEN', 'H'): ('qtable', ('V', 'H')),
        # ('qkurung', 'TABLE_OPEN', 'I'): ('qtable', ('V', 'I')),
        # ('qkurung', 'TABLE_OPEN', 'J'): ('qtable', ('V', 'J')),
        # ('qkurung', 'TABLE_OPEN', 'K'): ('qtable', ('V', 'K')),
        # ('qkurung', 'TABLE_OPEN', 'L'): ('qtable', ('V', 'L')),
        # ('qkurung', 'TABLE_OPEN', 'M'): ('qtable', ('V', 'M')),
        # ('qkurung', 'TABLE_OPEN', 'N'): ('qtable', ('V', 'N')),
        # ('qkurung', 'TABLE_OPEN', 'O'): ('qtable', ('V', 'O')),
        # ('qkurung', 'TABLE_OPEN', 'P'): ('qtable', ('V', 'P')),
        # ('qkurung', 'TABLE_OPEN', 'Q'): ('qtable', ('V', 'Q')),
        # ('qkurung', 'TABLE_OPEN', 'R'): ('qtable', ('V', 'R')),
        # ('qkurung', 'TABLE_OPEN', 'S'): ('qtable', ('V', 'S')),
        # ('qkurung', 'TABLE_OPEN', 'T'): ('qtable', ('V', 'T')),
        # ('qkurung', 'TABLE_OPEN', 'U'): ('qtable', ('V', 'U')),
        # ('qkurung', 'TABLE_OPEN', 'W'): ('qtable', ('V', 'W')),
        # ('qkurung', 'TABLE_OPEN', 'X'): ('qtable', ('V', 'X')),
        # ('qkurung', 'TABLE_OPEN', 'Y'): ('qtable', ('V', 'Y')),
        # ('qkurung', 'TABLE_CLOSE', 'V'): ('table', 'epsilon'),

        
        # ('qhtml', 'TR_OPEN', 'V'): ('qhtml', ('W', 'V')),
        # ('qhtml', 'TR_CLOSE', 'W'): ('qhtml', 'epsilon'),

        # ('qhtml', 'TD_OPEN', 'V'): ('qhtml', ('X', 'V')),
        # ('qhtml', 'TD_CLOSE', 'X'): ('qhtml', 'epsilon'),

        # ('qhtml', 'TH_OPEN', 'V'): ('qhtml', ('Y', 'V')),
        # ('qhtml', 'TH_CLOSE', 'Y'): ('qhtml', 'epsilon'),

        ('qhtml', '>', 'Y'): ('qhtml', 'epsilon')
    }
    final_states = {'q0'}
    pda = PDA(states, alphabet, stack_alphabet, initial_state, initial_stack_symbol, transitions, final_states)



    # pdaFilePath = sys.argv[1]
    # lines = fh.readFile(pdaFilePath)
    inputStringFilePath = sys.argv[1]
    token = lexer.createToken(inputStringFilePath)
    token = list(filter(lambda x: x != 'ENTER',token))
    print(token)
    print("\n")
    # token.remove('ENTER')
    print(token)
            
   
    # with open(inputStringFilePath, 'r') as inputStringFile:
    #     inputString = inputStringFile.read().replace('\n', '').replace(' ','')
    # print(inputString)
    # parsedLines = fh.parseFile(lines)
    # print('States: ', parsedLines['states'])
    # print('Input Symbols: ', parsedLines['input_symbols'])
    # print('Stack Symbols: ', parsedLines['stack_symbols'])
    # print('Starting State: ', parsedLines['starting_state'])
    # print('Starting Stack: ', parsedLines['starting_stack'])
    # print('Accepting States: ', parsedLines['accepting_states'])
    # print('Accept By: ', parsedLines['accept_by'])
    # print('Productions List:')
    # for production in parsedLines['productions']:
    #     print('\t', production)
    result = pda.process_input(token)
    if result:
        print("String HTML valid secara tag-structure-wise.")
    else:
        print("String HTML tidak valid secara tag-structure-wise.")




if __name__ == '__main__':
    main()
